import type { Metadata } from 'next';
import {
  Geist,
  Geist_Mono,
  Gowun_Dodum,
  Luxurious_Script,
  Hurricane,
  EB_Garamond,
} from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const gowunDodum = Gowun_Dodum({
  variable: '--font-gowun-dodum',
  subsets: ['latin'],
  weight: ['400'],
});

const luxuriousScript = Luxurious_Script({
  variable: '--font-luxurious-script',
  subsets: ['latin'],
  weight: ['400'],
});

const hurricane = Hurricane({
  variable: '--font-hurricane',
  subsets: ['latin'],
  weight: ['400'],
});

const enSerifGaramond = EB_Garamond({
  variable: '--font-en-serif-garamond',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gowunDodum.variable} ${luxuriousScript.variable} ${hurricane.variable} antialiased`}
        suppressHydrationWarning
      >
        {children}
      </body>
    </html>
  );
}
